name: 'Publish application'
on: push

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    
    env:
     PUBLISH_FOLDER: TableTennis/bin/Release/net8.0/publish/wwwroot

    name: Build and Deploy Job
    steps:
      - name: Set the name of the repo in env variable 
        run: 
            echo "REPO_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV
        
      - uses: actions/checkout@v3
      
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
   
      - name: Dotnet Publish
        run: 
            dotnet publish --configuration Release

      - name: Change base-tag in index.html to repo name
        run: sed -i 's/<base href="\/" \/>/<base href="\/${{ env.REPO_NAME }}\/" \/>/g' $GITHUB_WORKSPACE/$PUBLISH_FOLDER/index.html
  
      - name: copy index.html to 404.html
        run: cp $GITHUB_WORKSPACE/$PUBLISH_FOLDER/index.html $GITHUB_WORKSPACE/$PUBLISH_FOLDER/404.html
      
      - name: Add .nojekyll file
        run: touch $PUBLISH_FOLDER/.nojekyll
        
      - name: Deploy GitHub Pages action
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
            folder: TableTennis/bin/Release/net8.0/publish/wwwroot
